// Code generated by "libovsdb.modelgen"
// DO NOT EDIT.

package models

const ControllerTable = "Controller"

type (
	ControllerConnectionMode = string
	ControllerRole           = string
)

var (
	ControllerConnectionModeInBand    ControllerConnectionMode = "in-band"
	ControllerConnectionModeOutOfBand ControllerConnectionMode = "out-of-band"
	ControllerRoleMaster              ControllerRole           = "master"
	ControllerRoleOther               ControllerRole           = "other"
	ControllerRoleSlave               ControllerRole           = "slave"
)

// Controller defines an object in Controller table
type Controller struct {
	UUID                 string                    `ovsdb:"_uuid"`
	ConnectionMode       *ControllerConnectionMode `ovsdb:"connection_mode"`
	ControllerBurstLimit *int                      `ovsdb:"controller_burst_limit"`
	ControllerRateLimit  *int                      `ovsdb:"controller_rate_limit"`
	EnableAsyncMessages  *bool                     `ovsdb:"enable_async_messages"`
	ExternalIDs          map[string]string         `ovsdb:"external_ids"`
	InactivityProbe      *int                      `ovsdb:"inactivity_probe"`
	IsConnected          bool                      `ovsdb:"is_connected"`
	LocalGateway         *string                   `ovsdb:"local_gateway"`
	LocalIP              *string                   `ovsdb:"local_ip"`
	LocalNetmask         *string                   `ovsdb:"local_netmask"`
	MaxBackoff           *int                      `ovsdb:"max_backoff"`
	OtherConfig          map[string]string         `ovsdb:"other_config"`
	Role                 *ControllerRole           `ovsdb:"role"`
	Status               map[string]string         `ovsdb:"status"`
	Target               string                    `ovsdb:"target"`
}
